// Generated by CoffeeScript 1.8.0
var nodemailer;
nodemailer = require("nodemailer");
exports.index = function (req, res) {
    res.render("index", {
        title: "send to e-mail",
        para: req.param("para"),
        asunto: req.param("asunto"),
        texto: req.param("texto")
    });
};
exports.enviar = function (req, res) {
    var mailOptions, smtpTransport;
    smtpTransport = nodemailer.createTransport({
        service: "Gmail",
        auth: {
            user: "info@icrperusa.com",
            pass: "AHuachipa120"
        }
    });
    mailOptions = {
        from: "INFO ICR PERU S.A. ✔ <info@icrperusa.com>",
        to: req.body.email,
        subject: req.body.asunto,
        html: req.body.texto
    };
    smtpTransport.sendMail(mailOptions, function (error, response) {
        if (error) {
            console.log(error);
            res.render("error", {
                title: "Error al enviar el mail"
            });
        }
        else {
            console.log("Message sent: " + response.message);
            res.render("enviado", {
                title: "El mensaje fue enviado"
            });
        }
    });
};
exports.envelop = function (request, response) {
    var authProperty, emailOptions, fromProperty, smtpTransport;
    console.log(request.param("notdounsdf"));
    authProperty = new Object;
    fromProperty = "";
    if (request.param("pwdmailer") !== void 0) {
        console.log("success " + (request.param("name")));
        fromProperty = "" + (request.param("name").toString()) + " ✔ <" + (request.param("email").toString()) + "> ";
        console.log(fromProperty);
        authProperty = {
            user: request.param("email"),
            pass: request.param("pwdmailer")
        };
    }
    else {
        fromProperty = "INFO ICR PERU S.A. ✔ <logistica@icrperusa.com>";
        authProperty = {
            user: "info@icrperusa.com",
            pass: "AHuachipa120"
        };
    }
    smtpTransport = nodemailer.createTransport({
        service: "Gmail",
        auth: authProperty
    });
    emailOptions = {
        from: fromProperty,
        to: request.param("forsb"),
        subject: request.param("issue"),
        html: request.param("body")
    };
    if (request.param("ccb") !== void 0) {
        emailOptions.cc = request.param("ccb");
    }
    if (request.param("ccob") !== void 0) {
        emailOptions.cco = request.param("ccob");
    }
    smtpTransport.sendMail(emailOptions, function (error, result) {
        var context;
        context = new Object;
        if (error) {
            context.status = false;
            console.error("error " + error + ", result " + result);
        }
        else {
            context.status = true;
            console.log("Message sent: " + result.message);
        }
        response.setHeader("Content-Type", "application/json");
        response.type("application/json");
        response.jsonp(context);
    });
};
